export const SET_ACCOUNT = "SET_ACCOUNT"
export const SET_BALANCE = "SET_BALANCE"
export const SET_CONNECTION = "SET_CONNECTION"
export const SET_AVAX_INPUT = "SET_AVAX_INPUT"
export const SET_STK_AVAX_INPUT = "SET_STK_AVAX_INPUT"
export const SET_EXCHANGE_RATE = "SET_EXCHANGE_RATE"
export const SET_TRANSACTION_IN_PROGRESS = "SET_TRANSACTION_IN_PROGRESS"
export const UNSET_TRANSACTION_IN_PROGRESS = "UNSET_TRANSACTION_IN_PROGRESS"
export const SET_TRANSACTION_DETAILS = "SET_TRANSACTION_DETAILS"
export const UNSET_TRANSACTION_DETAILS = "UNSET_TRANSACTION_DETAILS"
export const SET_CONTRACT_DETAILS = "SET_CONTRACT_DETAILS"
export const SET_STAKE_UNSTAKE = "SET_STAKE_UNSTAKE"
export const SET_STK_AVAX_BALANCE = "SET_STK_AVAX_BALANCE"
export const SET_AVAX_BALANCE = "SET_AVAX_BALANCE"
export const RESET_BALANCE = "RESET_BALANCE"
export const RESET_INPUT = "RESET_INPUT"
export const SET_UNSTAKE_ALERT = "SET_UNSTAKE_ALERT"
export const FAILURE = "FAILED"
export const SUCCESS = "SUCCESS"
export const SET_DEVICE_DIMENSION = "SET_DEVICE_DIMENSION"
export const SET_DEVICE_TYPE = "SET_DEVICE_TYPE"
export const SET_METAMASK_INSTALLED = "SET_METAMASK_INSTALLED"
export const FETCH_CLAIM_TICKETS = "FETCH_CLAIM_TICKETS"
export const SET_INSTANT_UNSTAKE = "SET_INSTANT_UNSTAKE"
export const SET_UNSTAKE_NOW_FEE = "SET_UNSTAKE_NOW_FEE"
export const SET_DELAYED_UNSTAKE_FEE = "SET_DELAYED_UNSTAKE_FEE"
export const SET_REWARDS_FEE = "SET_REWARDS_FEE"
export const SET_DEPOSIT_FEE = "SET_DEPOSIT_FEE"






